// SPDX-License-Identifier: GPL-3.0-only
//
// Copyright © 2026 Two Factor Authentication Service, Inc.
//
// Licensed under the GNU General Public License v3.0.
// See the LICENSE file for details.

import PrefetchLink from '@/components/PrefetchLink';
import S from '../TermsOfUse/TermsOfUse.module.scss';
import Decors from '../../components/Decors';

/**
 * Privacy Policy legal page with hardcoded content.
 * @returns {import('preact').JSX.Element} The privacy policy page.
 */
export default function PrivacyPolicy() {
  return (
    <main className={S.terms}>
      <Decors />

      <div className='page-header'>
        <h1>2FAS Share Privacy Policy</h1>
        <p className={S.termsUpdated}>
          <strong>Last Updated:</strong> March 30th, 2026
        </p>
      </div>

      <article className={`${S.termsContent} page-box`}>
        <p>
          This Privacy Policy ("Policy") describes how Two Factor
          Authentication Service, Inc. ("Company", "2FAS", "we", "us", "our")
          collects, uses, stores, and protects information in connection with
          the 2FAS Share service available at share.2fas.com (the "Service").
          Capitalized terms not defined in this Policy have the meaning given
          to them in the{' '}
          <PrefetchLink href='/terms-of-use'>2FAS Share Terms of Use</PrefetchLink>{' '}
          ("<PrefetchLink href='/terms-of-use'>Terms</PrefetchLink>").
        </p>

        <p>
          By accessing or using the Service, you acknowledge that you have
          read and understood this Policy. If you do not agree with this
          Policy, please do not use the Service.
        </p>

        <h2>1. Zero-Knowledge by Design</h2>

        <p>
          The Service is built on a{' '}
          <strong>zero-knowledge architecture</strong>, described in detail in
          Section 5 of the{' '}
          <PrefetchLink href='/terms-of-use'>Terms</PrefetchLink>. The most important things
          you should know about how we handle your data:
        </p>

        <ul>
          <li>
            All Shared Data is <strong>encrypted on the Sender's device</strong>{' '}
            before it is transmitted to our servers.
          </li>
          <li>
            The decryption key is{' '}
            <strong>never transmitted to our servers</strong>. It stays on the
            user's device.
          </li>
          <li>
            If a Sender enables the optional password feature, the password is
            processed on the user's device and is{' '}
            <strong>never sent to or accessible by us</strong>.
          </li>
          <li>
            As a result,{' '}
            <strong>
              we cannot read, decrypt, recover, or otherwise access the content
              of Shared Data
            </strong>
            , and we cannot recover lost decryption keys or passwords.
          </li>
        </ul>

        <p>
          What we store on our servers is an opaque, encrypted blob whose
          contents we have no technical means to view.
        </p>

        <h2>2. Information We Process</h2>

        <p>
          We deliberately collect as little information as possible. The
          Service does <strong>not</strong> require an account, does{' '}
          <strong>not</strong> ask for your name or email address, and does{' '}
          <strong>not</strong> use analytics, advertising identifiers, or other
          tracking technologies to profile users or follow them across sites.
        </p>

        <p>The categories of information we process are:</p>

        <h3>2.1 Encrypted Shared Data</h3>

        <p>
          The encrypted payload that the Sender uploads, together with the
          parameters the Sender chooses (availability period, single-use vs.
          multi-use flag, and whether password protection is enabled). We have
          no access to the plaintext content, decryption key, or password.
        </p>

        <h3>2.2 Access Logs</h3>

        <p>
          As part of normal Service operation, standard access logs
          ("<strong>Access Logs</strong>") are generated by our
          infrastructure, as described in Section 4 of the{' '}
          <PrefetchLink href='/terms-of-use'>Terms</PrefetchLink>. Access Logs may include:
        </p>

        <ul>
          <li>IP address</li>
          <li>Timestamp of the request</li>
          <li>Browser user-agent string</li>
          <li>The requested URL path</li>
        </ul>

        <p>
          Access Logs <strong>do not</strong> contain any Shared Data,
          decryption keys, or passwords. As explained in Section 1, the
          decryption key never leaves the user's device, and therefore never
          reaches our logs.
        </p>

        <p>
          Access Logs are retained for a maximum of{' '}
          <strong>three (3) months</strong> and are used{' '}
          <strong>solely</strong> for security and abuse prevention purposes,
          unless a longer retention period is required by applicable law (for
          example, in connection with an active security incident or a lawful
          order from a competent authority).
        </p>

        <h3>2.3 Communications You Send Us</h3>

        <p>
          The Service does not ask for or store your email address. However,
          if you choose to contact us at{' '}
          <a href='mailto:help@2fas.com'>help@2fas.com</a> or{' '}
          <a href='mailto:privacy@2fas.com'>privacy@2fas.com</a>, we will
          receive the email address you write from and the contents of your
          message. We use this information only to respond to and handle your
          request. We do <strong>not</strong> use your email address for
          marketing, newsletters, or any other purpose.
        </p>

        <h2>3. How We Use Information</h2>

        <p>
          We use the information described in Section 2 only for the following
          purposes:
        </p>

        <ul>
          <li>
            To operate the Service — storing and delivering Encrypted Shared
            Data and enforcing the expiration and single-use / multi-use rules
            chosen by the Sender.
          </li>
          <li>
            To keep the Service secure — Access Logs are used{' '}
            <strong>solely</strong> to detect and prevent attacks, malware
            distribution, scraping, and other activity that violates the{' '}
            <PrefetchLink href='/terms-of-use'>Terms</PrefetchLink>.
          </li>
          <li>
            To respond to questions or requests you send to us.
          </li>
        </ul>

        <p>
          Separately from the purposes above, we may be legally compelled to
          disclose specific information in response to valid legal requests
          from competent authorities. The limited circumstances under which
          any such disclosure may occur are described in Section 8.
        </p>

        <p>
          We do <strong>not</strong> use information for advertising. We do{' '}
          <strong>not</strong> build user profiles. We do{' '}
          <strong>not</strong> share information with advertisers or data
          brokers.
        </p>

        <h2>4. No Tracking or Analytics</h2>

        <p>
          We do not use analytics platforms, advertising tags, social plugins,
          browser fingerprinting, or any other technologies designed to
          profile users or follow them across websites or sessions.
        </p>

        <p>
          Your browser may, of its own accord, store the URL of pages you
          visit (including links to Shared Data) in its history. That storage
          is controlled entirely by you and your browser.
        </p>

        <h2>5. Where Data Is Stored</h2>

        <p>
          Encrypted Shared Data is stored on infrastructure operated by{' '}
          <strong>Amazon Web Services (AWS)</strong> in the{' '}
          <strong>US-East-2 region (United States)</strong>. AWS acts as our
          hosting sub-processor for storage and compute, and handles the
          Access Logs described in Section 2.2.
        </p>

        <p>
          Requests to share.2fas.com are routed through{' '}
          <strong>Cloudflare, Inc.</strong>, which we use as a reverse proxy,
          content delivery network, and DDoS-protection layer in front of our
          AWS origin. Traffic passes through Cloudflare's global network of
          edge servers (which may include servers located in or outside your
          country) before reaching AWS. In the course of providing these
          services, Cloudflare processes the same categories of information
          that appear in our Access Logs (see Section 2.2) as well as the
          encrypted payloads transiting between the user's device and the
          origin. Because the decryption key never leaves the user's device,
          Cloudflare — like us — has no ability to read the content of Shared
          Data.
        </p>

        <p>
          Both AWS and Cloudflare act as sub-processors and are contractually
          bound to appropriate security and confidentiality obligations.
        </p>

        <p>
          If you access the Service from outside the United States, you
          understand and agree that your information will be transferred to
          and processed in the United States and at the edge locations used by
          Cloudflare to deliver the Service. Where required by applicable law
          (for example, for transfers from the EEA, UK, or Switzerland), we
          rely on the European Commission's Standard Contractual Clauses and
          equivalent safeguards offered by our sub-processors to provide an
          adequate level of protection.
        </p>

        <h2>6. How Long We Keep Data</h2>

        <h3>6.1 Encrypted Shared Data</h3>

        <p>
          Encrypted Shared Data is retained according to the rules described
          in <strong>Section 4 of the{' '}
          <PrefetchLink href='/terms-of-use'>Terms</PrefetchLink></strong>{' '}
          ("Data Availability, Retention, and Access Controls"). In summary:
        </p>

        <ul>
          <li>
            <strong>Single-use links</strong> — the encrypted payload is
            invalidated as soon as a Recipient initiates retrieval, and is
            then removed from our systems.
          </li>
          <li>
            <strong>Multi-use links</strong> — the encrypted payload is
            removed from our systems at the expiration time chosen by the
            Sender.
          </li>
          <li>
            In every case, once the link is invalidated or expired, the
            corresponding encrypted payload is{' '}
            <strong>deleted from our active storage</strong> in the ordinary
            course of operations. Residual copies may persist in routine
            system backups for a limited period consistent with our backup
            rotation schedule before being overwritten.
          </li>
        </ul>

        <p>
          We do <strong>not</strong> retain encrypted Shared Data beyond what
          is necessary to deliver it to the Recipient under the conditions
          chosen by the Sender.
        </p>

        <h3>6.2 Access Logs</h3>

        <p>
          As noted in Section 2.2 and in Section 4 of the{' '}
          <PrefetchLink href='/terms-of-use'>Terms</PrefetchLink>, Access Logs are retained
          for a maximum of <strong>three (3) months</strong>, after which they
          are deleted. Records that we are legally required to retain longer
          are kept only for as long as that obligation requires.
        </p>

        <h3>6.3 Support Communications</h3>

        <p>
          Email correspondence is retained for as long as reasonably necessary
          to handle your inquiry and to keep a record of how it was resolved.
        </p>

        <h3>6.4 No Obligation to Preserve Data</h3>

        <p>
          We have <strong>no obligation</strong> to preserve, archive, or
          otherwise retain any information beyond the retention periods
          described in this Section, except where preservation is required by
          applicable law or by a valid order from a competent authority. We
          are under no obligation to honor private preservation requests,
          including requests made in anticipation of or during civil
          litigation between third parties.
        </p>

        <h2>7. How We Protect Information</h2>

        <p>
          In addition to the zero-knowledge architecture described in
          Section 1, we apply technical and organizational measures
          appropriate to the risk, including:
        </p>

        <ul>
          <li>
            TLS/HTTPS encryption for all traffic between users and the Service
          </li>
          <li>
            Encryption at rest of stored payloads on AWS infrastructure
          </li>
          <li>
            Strict access controls and the principle of least privilege for
            personnel with operational access to the hosting environment
          </li>
        </ul>

        <p>
          No system is completely secure. As explained in the{' '}
          <PrefetchLink href='/terms-of-use'>Terms</PrefetchLink>, the security of Shared
          Data also depends on how Senders and Recipients handle links,
          passwords, and their own devices.
        </p>

        <h2>8. Disclosure to Third Parties</h2>

        <p>
          We do not sell, rent, or trade the Access Logs described in
          Section 2.2, and we do not share them for advertising, marketing, or
          profiling purposes. As those terms are defined under the California
          Consumer Privacy Act (CCPA/CPRA), we do <strong>not</strong> "sell"
          or "share" Access Logs or any other information. We disclose
          information only in the following limited circumstances:
        </p>

        <ul>
          <li>
            <strong>Service providers (sub-processors).</strong> Amazon Web
            Services, Inc. provides the hosting infrastructure, and
            Cloudflare, Inc. provides the reverse proxy, CDN, and
            DDoS-protection layer, as described in Section 5. Sub-processors
            are contractually bound to appropriate confidentiality, security,
            and data protection obligations.
          </li>
          <li>
            <strong>Legal requests and safety.</strong> We may disclose
            information if we are required to do so by law, subpoena, court
            order, or other valid legal process, or if we believe in good
            faith that disclosure is reasonably necessary to (i) protect the
            rights, property, or safety of 2FAS, our users, or the public,
            (ii) investigate or respond to suspected fraud, abuse, or
            violations of the{' '}
            <PrefetchLink href='/terms-of-use'>Terms</PrefetchLink>, or (iii) enforce the{' '}
            <PrefetchLink href='/terms-of-use'>Terms</PrefetchLink>. Because of the
            zero-knowledge architecture, we cannot produce the plaintext
            content of Shared Data in response to any such request.
          </li>
          <li>
            <strong>Corporate transactions.</strong> If 2FAS is involved in a
            merger, acquisition, financing, reorganization, bankruptcy, or
            sale of assets, information may be transferred as part of that
            transaction. We will require any successor to honor the
            commitments we have made in this Policy.
          </li>
        </ul>

        <h2>9. Children's Privacy</h2>

        <p>
          The Service is not directed to children under the age of 13 (or
          under 16 in jurisdictions where that higher threshold applies). We
          do not knowingly collect information from children. If you believe a
          child has used the Service in a way that caused information relating
          to them to reach us, please contact us at{' '}
          <a href='mailto:privacy@2fas.com'>privacy@2fas.com</a> and we will
          take appropriate steps.
        </p>

        <h2>10. Your Rights</h2>

        <p>
          Depending on where you live, applicable data protection laws (such
          as the GDPR in the EEA/UK or the CCPA/CPRA in California) may give
          you certain rights with respect to information that relates to you,
          including the rights of access, rectification, erasure, restriction,
          objection, and lodging a complaint with a supervisory authority.
        </p>

        <p>
          You should know, however, what these rights can realistically mean
          in the context of this Service:
        </p>

        <ul>
          <li>
            The Service has <strong>no user accounts</strong>. We do not know
            your name, email, or any other identifier that links you to the
            data we process.
          </li>
          <li>
            The only information we hold that could theoretically relate to
            you is the Access Logs described in Section 2.2, which are kept
            for no more than three months and are not linked by us to any
            account, name, or other direct identifier.
          </li>
          <li>
            For that reason, we generally cannot verify that a rights request
            relates to a specific individual.
          </li>
        </ul>

        <p>
          If you believe you have a rights request that can be meaningfully
          fulfilled, please contact us at{' '}
          <a href='mailto:privacy@2fas.com'>privacy@2fas.com</a> and we will
          respond in accordance with applicable law.
        </p>

        <h2>11. International Users</h2>

        <p>
          The Service is operated from the United States. By using the
          Service, you understand that your information will be processed in
          the United States, which may have data protection laws different
          from those of your jurisdiction. See Section 5 for information
          about safeguards used for cross-border transfers.
        </p>

        <h2>12. Third-Party Links and Recipients</h2>

        <p>
          A Sender chooses with whom to share a link. Once a link leaves our
          systems, how it is transmitted (email, messenger, paper, etc.) and
          who ultimately receives it is outside our control. The privacy
          practices of any third-party communication channel used to share a
          link are governed by that third party, not by this Policy.
        </p>

        <h2>13. Changes to This Policy</h2>

        <p>
          We may update this Policy from time to time. When we do, we will
          revise the "Last Updated" date at the top of the Policy and post
          the updated version at share.2fas.com. Material changes will be
          highlighted in a reasonable manner. Your continued use of the
          Service after the updated Policy takes effect constitutes acceptance
          of the updated Policy.
        </p>

        <h2>14. Governing Law and Dispute Resolution</h2>

        <p>
          Any claim or dispute relating to this Policy, or to how we handle
          information in connection with the Service, is governed by and
          subject to the dispute resolution, arbitration, class action waiver,
          and governing law provisions set out in the{' '}
          <PrefetchLink href='/terms-of-use'>Terms</PrefetchLink> (in particular, Sections 19
          and 20 of the{' '}
          <PrefetchLink href='/terms-of-use'>Terms</PrefetchLink>). By using the Service, you
          agree that those provisions apply to privacy-related disputes in
          the same way they apply to other disputes arising out of or
          relating to the Service.
        </p>

        <h2>15. Contact Us</h2>

        <p>
          If you have questions, requests, or concerns about this Policy or
          about how we handle information, please contact us:
        </p>

        <ul>
          <li>
            <strong>Privacy inquiries:</strong>{' '}
            <a href='mailto:privacy@2fas.com'>privacy@2fas.com</a>
          </li>
        </ul>

        <p>
          <strong>Two Factor Authentication Service, Inc.</strong>
        </p>

      </article>
    </main>
  );
}
